apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secretsmanager
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "int-preproduction-use1-shared-eks-ecommerce"
        objectType: "secretsmanager"
  secretObjects:
  - secretName: ecommerce-db-secrets
    type: Opaque
    data:
    - objectName: DB_NAME
      key: DB_NAME
    - objectName: DB_USER
      key: DB_USER
    - objectName: DB_PASS
      key: DB_PASS
    - objectName: DB_HOST
      key: DB_HOST
