apiVersion: apps/v1
kind: Deployment
metadata:
  name: hway-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hway-app3
  template:
    metadata:
      labels:
        app: hway-app3
    spec:
      containers:
      - name: hway
        image: njibrigthain100/brigthain:hwv2
        ports:
        - containerPort: 80
