apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate # This means when updating the deployment, it will terminate the existing pod before creating a new one.
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: dbpassword11
        ports:
        - containerPort: 3306
          name: mysql # This is just a name for the port, can be anything
        volumeMounts:
        # You mount the volumes here
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-persistent-storage2
          mountPath: /var/lib/mysql # Thi is is the path where MySQL stores its data
        - name: usermanagement-dbcreation-script
          mountPath: /docker-entrypoint-initdb.d #https://hub.docker.com/_/mysql Refer Initializing a fresh instance                                            
      volumes:
      # You create the volumes here and then mount them in the container above
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: ebs-mysql-pv-claim
      - name: mysql-persistent-storage2
        persistentVolumeClaim:
          claimName: ebs-mysql-pv-claim2 # This is the PVC we created earlier
      - name: usermanagement-dbcreation-script
        configMap:
          name: usermanagement-dbcreation-script
