apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  labels:
    app: app
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: microservice
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: micorservice # This annotation is used to group multiple ingresses to the same ALB
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    ## SSL
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:730335294148:certificate/1e081677-3567-4cf2-9739-b11927661038
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    ## Network Security
    alb.ingress.kubernetes.io/security-groups: sg-056e0f9a46dc3782d
    ## External DNS
    external-dns.alpha.kubernetes.io/hostname: app.shared.cognitechllc.org
spec:
  ingressClassName: multi-app-ingress-class
  rules:
  - host: app.shared.cognitechllc.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app-nodeport-service
            port:
              number: 80

# You can also create a separate ingress for account service as shown below
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: account-ingress
  labels:
    app: account
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: microservice
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: micorservice # This annotation is used to group multiple ingresses to the same ALB
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    ## SSL
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:730335294148:certificate/1e081677-3567-4cf2-9739-b11927661038
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    ## Network Security
    alb.ingress.kubernetes.io/security-groups: sg-056e0f9a46dc3782d
    ## External DNS
    external-dns.alpha.kubernetes.io/hostname: account.shared.cognitechllc.org
spec:
  ingressClassName: multi-app-ingress-class
  rules:
  - host: account.shared.cognitechllc.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: account-nodeport-service
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hway-ingress
  labels:
    app: hway
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: microservice
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/group.name: micorservice # This annotation is used to group multiple ingresses to the same ALB
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/success-codes: '200'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
    ## SSL
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:730335294148:certificate/1e081677-3567-4cf2-9739-b11927661038
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01
    alb.ingress.kubernetes.io/ssl-redirect: "443"
    ## Network Security
    alb.ingress.kubernetes.io/security-groups: sg-056e0f9a46dc3782d
    ## External DNS
    external-dns.alpha.kubernetes.io/hostname: hway.shared.cognitechllc.org
spec:
  ingressClassName: multi-app-ingress-class
  rules:
  - host: hway.shared.cognitechllc.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hway-nodeport-service
            port:
              number: 80
