apiVersion: v1
kind: Pod
metadata:
  name: nginx # Name of the Pod
spec:
  # short for specification
  containers:
  - name: my-first-container
    image: nginx:latest # Use the official Nginx image from Docker Hub
    ports:
    - containerPort: 80 # This container listens on port 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
