apiVersion: apps/v1
kind: Deployment
metadata:
  name: usermgmt-microservice
  labels:
    app: usermgmt-restapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-restapp
  template:
    metadata:
      labels:
        app: usermgmt-restapp
    spec:
      containers:
      - name: usermgmt-restapp
        image: stacksimplify/kube-usermanagement-microservice:1.0.0
        ports:
        - containerPort: 8095
        env:
        - name: DB_HOSTNAME
          value: "mysql"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME # What schema to connect to
          value: "usermgmt" # This was created by the init script we mounted in mysql pod. Created by the configmap  
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: "dbpassword11"
